import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../controllers/admin_bins_controller.dart';
import '../../core/label_format.dart';
import '../../models/bin_model.dart';
import '../../services/bin_admin_service.dart';
import '../shared/app_shell.dart';

/// Bin registration and QR generation (F2.1).
///
/// Coordinates are typed here. Capturing them from a live GPS fix while
/// standing at the bin is the mobile refinement and is not wired yet — typed
/// entry is what the web build wants regardless, and it is enough to register
/// the bins a demo needs.
class AdminBinsView extends ConsumerStatefulWidget {
  const AdminBinsView({super.key});

  static const double _maxContentWidth = 820;

  @override
  ConsumerState<AdminBinsView> createState() => _AdminBinsViewState();
}

class _AdminBinsViewState extends ConsumerState<AdminBinsView> {
  final _label = TextEditingController();
  final _lat = TextEditingController();
  final _lng = TextEditingController();
  final _radius = TextEditingController(text: '50');

  bool _saving = false;
  List<String> _problems = const [];

  @override
  void dispose() {
    _label.dispose();
    _lat.dispose();
    _lng.dispose();
    _radius.dispose();
    super.dispose();
  }

  Future<void> _register() async {
    final lat = double.tryParse(_lat.text.trim());
    final lng = double.tryParse(_lng.text.trim());
    final radius = double.tryParse(_radius.text.trim());

    final local = <String>[
      if (_label.text.trim().isEmpty) 'Bin label is required.',
      if (lat == null) 'Latitude must be a number.',
      if (lng == null) 'Longitude must be a number.',
      if (radius == null) 'Radius must be a number.',
    ];

    if (local.isNotEmpty) {
      setState(() => _problems = local);
      return;
    }

    setState(() {
      _saving = true;
      _problems = const [];
    });

    try {
      final bin = await ref.read(adminBinActionsProvider).register(
            label: _label.text.trim(),
            lat: lat!,
            lng: lng!,
            radiusMeters: radius!,
          );

      if (!mounted) return;
      setState(() {
        _saving = false;
        _label.clear();
        _lat.clear();
        _lng.clear();
        _radius.text = '50';
      });

      await _showQr(bin);
    } on BinAdminException catch (error) {
      if (!mounted) return;
      setState(() {
        _saving = false;
        _problems =
            error.problems.isEmpty ? [error.message] : error.problems;
      });
    }
  }

  Future<void> _showQr(BinModel bin) async {
    await showDialog<void>(
      context: context,
      builder: (context) => _QrDialog(bin: bin),
    );
  }

  Future<void> _toggle(BinModel bin) async {
    final id = bin.id;
    if (id == null) return;

    try {
      await ref
          .read(adminBinActionsProvider)
          .setActive(binId: id, active: !bin.active);
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            bin.active ? '${bin.label} closed.' : '${bin.label} reopened.',
          ),
        ),
      );
    } on BinAdminException catch (error) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text(error.message)));
    }
  }

  @override
  Widget build(BuildContext context) {
    final async = ref.watch(allBinsProvider);
    final theme = Theme.of(context);

    return AppShell(
      title: 'Bins',
      child: Center(
        child: ConstrainedBox(
          constraints:
              const BoxConstraints(maxWidth: AdminBinsView._maxContentWidth),
          child: ListView(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 32),
            children: [
              Text('Register a bin',
                  style: theme.textTheme.titleMedium
                      ?.copyWith(fontWeight: FontWeight.bold)),
              const SizedBox(height: 4),
              Text(
                'The QR payload is generated by the server, so it is unique '
                'across every bin. Print the code and attach it to the bin.',
                style: theme.textTheme.bodySmall
                    ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
              ),
              const SizedBox(height: 14),
              TextField(
                controller: _label,
                decoration: const InputDecoration(
                  labelText: 'Label',
                  hintText: 'Merul Badda — Block C gate',
                  isDense: true,
                ),
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _lat,
                      keyboardType: const TextInputType.numberWithOptions(
                          decimal: true, signed: true),
                      inputFormatters: [
                        FilteringTextInputFormatter.allow(RegExp(r'[0-9.\-]')),
                      ],
                      decoration: const InputDecoration(
                        labelText: 'Latitude',
                        hintText: '23.7808',
                        isDense: true,
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: TextField(
                      controller: _lng,
                      keyboardType: const TextInputType.numberWithOptions(
                          decimal: true, signed: true),
                      inputFormatters: [
                        FilteringTextInputFormatter.allow(RegExp(r'[0-9.\-]')),
                      ],
                      decoration: const InputDecoration(
                        labelText: 'Longitude',
                        hintText: '90.4074',
                        isDense: true,
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  SizedBox(
                    width: 120,
                    child: TextField(
                      controller: _radius,
                      keyboardType: TextInputType.number,
                      inputFormatters: [
                        FilteringTextInputFormatter.digitsOnly,
                      ],
                      decoration: const InputDecoration(
                        labelText: 'Radius',
                        suffixText: 'm',
                        isDense: true,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 6),
              Text(
                'A tight radius is a stronger proof of presence. 50 m suits a '
                'street bin; an open compound may need more.',
                style: theme.textTheme.bodySmall
                    ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
              ),
              if (_problems.isNotEmpty) ...[
                const SizedBox(height: 12),
                for (final problem in _problems)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 4),
                    child: Text(
                      '• $problem',
                      style: theme.textTheme.bodySmall
                          ?.copyWith(color: theme.colorScheme.error),
                    ),
                  ),
              ],
              const SizedBox(height: 14),
              FilledButton.icon(
                onPressed: _saving ? null : _register,
                icon: _saving
                    ? const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(strokeWidth: 2))
                    : const Icon(Icons.add_location_alt_outlined),
                label: Text(_saving ? 'Registering…' : 'Register bin'),
              ),
              const SizedBox(height: 28),
              Text('Registered bins',
                  style: theme.textTheme.titleMedium
                      ?.copyWith(fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              async.when(
                loading: () => const Padding(
                  padding: EdgeInsets.all(24),
                  child: Center(child: CircularProgressIndicator()),
                ),
                error: (error, _) => Text('Bins did not load: $error'),
                data: (bins) {
                  if (bins.isEmpty) {
                    return Text(
                      'No bins yet. Nothing can be scanned until one exists.',
                      style: theme.textTheme.bodySmall,
                    );
                  }
                  final sorted = [...bins]
                    ..sort((a, b) => a.label.compareTo(b.label));
                  return Column(
                    children: [
                      for (final bin in sorted)
                        _BinCard(
                          bin: bin,
                          onShowQr: () => _showQr(bin),
                          onToggle: () => _toggle(bin),
                        ),
                    ],
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _BinCard extends StatelessWidget {
  const _BinCard({
    required this.bin,
    required this.onShowQr,
    required this.onToggle,
  });

  final BinModel bin;
  final VoidCallback onShowQr;
  final VoidCallback onToggle;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Row(
          children: [
            Icon(
              bin.active ? Icons.delete_outline : Icons.block,
              color: bin.active
                  ? theme.colorScheme.primary
                  : theme.colorScheme.onSurfaceVariant,
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(bin.label,
                      style: theme.textTheme.titleSmall
                          ?.copyWith(fontWeight: FontWeight.w700)),
                  const SizedBox(height: 2),
                  Text(
                    '${bin.lat.toStringAsFixed(5)}, '
                    '${bin.lng.toStringAsFixed(5)} · '
                    '${bin.radiusMeters.round()} m'
                    '${bin.active ? '' : ' · closed'}',
                    style: theme.textTheme.bodySmall
                        ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
                  ),
                  if (bin.createdAt != null)
                    Text(
                      'Registered ${formatAge(bin.createdAt)}',
                      style: theme.textTheme.labelSmall
                          ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
                    ),
                ],
              ),
            ),
            IconButton(
              tooltip: 'Show QR code',
              onPressed: onShowQr,
              icon: const Icon(Icons.qr_code_2),
            ),
            TextButton(
              onPressed: onToggle,
              child: Text(bin.active ? 'Close' : 'Reopen'),
            ),
          ],
        ),
      ),
    );
  }
}

class _QrDialog extends StatelessWidget {
  const _QrDialog({required this.bin});

  final BinModel bin;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AlertDialog(
      title: Text(bin.label),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // White background regardless of theme — a dark-mode QR code
          // photographs badly and some scanners refuse it outright.
          Container(
            padding: const EdgeInsets.all(16),
            color: Colors.white,
            child: QrImageView(
              data: bin.qrPayload,
              version: QrVersions.auto,
              size: 220,
              backgroundColor: Colors.white,
            ),
          ),
          const SizedBox(height: 14),
          SelectableText(
            bin.qrPayload,
            textAlign: TextAlign.center,
            style: theme.textTheme.bodySmall
                ?.copyWith(fontFamily: 'monospace'),
          ),
          const SizedBox(height: 8),
          Text(
            'Print this and attach it to the bin. On the web build, Ctrl+P '
            'prints the page.',
            textAlign: TextAlign.center,
            style: theme.textTheme.bodySmall
                ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
          ),
        ],
      ),
      actions: [
        TextButton(
          onPressed: () {
            Clipboard.setData(ClipboardData(text: bin.qrPayload));
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Payload copied.')),
            );
          },
          child: const Text('Copy payload'),
        ),
        FilledButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Done'),
        ),
      ],
    );
  }
}
