// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWED-i46EZefYni4HVRmkYnpN6cf7EoCs',
    appId: '1:430187570326:web:59722027d6242f17f2ceb7',
    messagingSenderId: '430187570326',
    projectId: 'chokro-30887',
    authDomain: 'chokro-30887.firebaseapp.com',
    storageBucket: 'chokro-30887.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKAT7xOOII0qYCCVG07_rI8T9BQZNFTRg',
    appId: '1:430187570326:android:35a6273222fb02e3f2ceb7',
    messagingSenderId: '430187570326',
    projectId: 'chokro-30887',
    storageBucket: 'chokro-30887.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp1Yg9QxjWTgX7cudD9e2TuCKeo3ja4ok',
    appId: '1:430187570326:ios:7fa9cfb8d3e7cfb5f2ceb7',
    messagingSenderId: '430187570326',
    projectId: 'chokro-30887',
    storageBucket: 'chokro-30887.firebasestorage.app',
    iosClientId:
        '430187570326-3mpquf925jubtvr86bd86oto8h4jqt79.apps.googleusercontent.com',
    iosBundleId: 'com.arnish.chokro',
  );
}
