import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/bin_model.dart';
import '../services/bin_admin_service.dart';
import '../services/bin_service.dart';
import '../services/location_service.dart';

/// Uniquely named to avoid colliding with any `binServiceProvider` already
/// declared for the scan flow. `BinService` is stateless, so a second instance
/// costs nothing.
final adminBinServiceProvider = Provider<BinService>((ref) => BinService());

final binAdminServiceProvider = Provider<BinAdminService>(
  (ref) => BinAdminService(),
);

/// Own instance, for the same reason as [adminBinServiceProvider]: the disposal
/// flow declares its own `locationServiceProvider`, `LocationService` is
/// stateless, and a second instance costs nothing — while bin administration
/// stays independent of the disposal flow's providers.
final binLocationServiceProvider = Provider<LocationService>(
  (ref) => LocationService(),
);

/// Every bin including closed ones (F2.1).
///
/// Read straight from Firestore rather than through the server: rules allow any
/// signed-in user to read `bins`, and a live stream means a newly registered bin
/// appears without a refresh.
final allBinsProvider = StreamProvider.autoDispose<List<BinModel>>((ref) {
  return ref.watch(adminBinServiceProvider).watchAllBins();
});

/// Registration and open/close actions, both server-side.
class AdminBinActions {
  AdminBinActions(this._ref);

  final Ref _ref;

  /// Returns the registered bin, whose `qrPayload` is generated by the server —
  /// uniqueness is not something a client can guarantee.
  Future<BinModel> register({
    required String label,
    required double lat,
    required double lng,
    required double radiusMeters,
  }) {
    return _ref
        .read(binAdminServiceProvider)
        .createBin(
          label: label,
          lat: lat,
          lng: lng,
          radiusMeters: radiusMeters,
        );
  }

  Future<void> setActive({required String binId, required bool active}) {
    return _ref
        .read(binAdminServiceProvider)
        .setActive(binId: binId, active: active);
  }

  /// A GPS fix for the bin being registered (F2.1: "GPS captured on site").
  ///
  /// The brief calls bin registration mobile-first for this reason: an
  /// administrator standing at the bin can capture its position, where typing
  /// coordinates means reading them off a map later and guessing.
  ///
  /// This fix matters more than the one taken during a disposal. A disposal's
  /// coordinates are checked once, against this bin; *these* coordinates become
  /// the centre of the geofence every future submission at this bin is measured
  /// against, so an error here is inherited by all of them and nothing later
  /// will reveal it. Hence the tighter accuracy warning in the view.
  Future<LocationResult> captureLocation() {
    return _ref.read(binLocationServiceProvider).getCurrentLocation();
  }

  Future<void> openLocationSettings() =>
      _ref.read(binLocationServiceProvider).openLocationSettings();

  Future<void> openAppSettings() =>
      _ref.read(binLocationServiceProvider).openSettings();
}

final adminBinActionsProvider = Provider<AdminBinActions>(
  (ref) => AdminBinActions(ref),
);
