import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/bin_model.dart';
import '../services/bin_admin_service.dart';
import '../services/bin_service.dart';

/// Uniquely named to avoid colliding with any `binServiceProvider` already
/// declared for the scan flow. `BinService` is stateless, so a second instance
/// costs nothing.
final adminBinServiceProvider = Provider<BinService>((ref) => BinService());

final binAdminServiceProvider =
    Provider<BinAdminService>((ref) => BinAdminService());

/// Every bin including closed ones (F2.1).
///
/// Read straight from Firestore rather than through the server: rules allow any
/// signed-in user to read `bins`, and a live stream means a newly registered bin
/// appears without a refresh.
final allBinsProvider = StreamProvider.autoDispose<List<BinModel>>((ref) {
  return ref.watch(adminBinServiceProvider).watchAllBins();
});

/// Registration and open/close actions, both server-side.
class AdminBinActions {
  AdminBinActions(this._ref);

  final Ref _ref;

  /// Returns the registered bin, whose `qrPayload` is generated by the server —
  /// uniqueness is not something a client can guarantee.
  Future<BinModel> register({
    required String label,
    required double lat,
    required double lng,
    required double radiusMeters,
  }) {
    return _ref.read(binAdminServiceProvider).createBin(
          label: label,
          lat: lat,
          lng: lng,
          radiusMeters: radiusMeters,
        );
  }

  Future<void> setActive({required String binId, required bool active}) {
    return _ref
        .read(binAdminServiceProvider)
        .setActive(binId: binId, active: active);
  }
}

final adminBinActionsProvider =
    Provider<AdminBinActions>((ref) => AdminBinActions(ref));
