/**
 * Chokro — Firebase App Check enforcement (SEC-10, NFR-E-9).
 *
 * WHAT THIS CLOSES
 * Without App Check, every endpoint on this service accepts traffic from
 * anything holding a valid ID token — a browser, a curl loop, a scraper, a
 * script someone wrote against the API after reading the Flutter web bundle.
 * Authentication proves *who* is asking. App Check proves the request came from
 * an app build this project published. They answer different questions, and the
 * producer portal is where the second one stops being deferrable: a corporate
 * compliance dataset with a rate limit and no attestation is a dataset with a
 * schedule attached to it.
 *
 * WHY IT IS A FLAG AND NOT ALWAYS ON
 * Turning enforcement on before the clients are provisioned locks every real
 * user out — a web build needs a reCAPTCHA Enterprise site key, Android needs
 * Play Integrity, iOS needs App Attest, and each is a console step this code
 * cannot perform. So enforcement is a deployment decision, made by setting
 * `APP_CHECK_ENFORCED=true`, and NFR-E-9 makes setting it release-blocking
 * before the first real producer is onboarded rather than a follow-up.
 *
 * The flag is deliberately fail-closed in the other direction too: once
 * enforcement is on, a missing or unverifiable token is a refusal, never a
 * warning. A control that logs and continues is not a control.
 *
 * WHAT IT DOES WHEN OFF
 * Nothing, except say so once at startup. It does not verify-and-ignore: a
 * verification that never blocks anything spends a round trip per request to
 * produce a log line nobody reads.
 */

const { admin } = require('./firebase');

/** Whether enforcement is on for this deployment. */
function isEnforced() {
  return process.env.APP_CHECK_ENFORCED === 'true';
}

/**
 * Routes exempt from enforcement even when it is on.
 *
 * Two of them, and each for a stated reason:
 *
 * `/health` is what Render pings and what a person curls when the free instance
 * has gone to sleep. An attested health check is a health check that cannot be
 * used to diagnose an outage.
 *
 * `/epr/invitations/redeem` is reached by someone who has just clicked a link
 * in their email, possibly in a browser that has never loaded the app. There is
 * no app instance to attest. Its protection is the 256-bit single-use token and
 * the per-IP limiter, which is why both of those are as tight as they are
 * (SEC-8).
 */
const EXEMPT_PATHS = Object.freeze([
  '/health',
  '/epr/password-policy',
  '/epr/invitations/redeem',
]);

function isExempt(path) {
  return EXEMPT_PATHS.includes(path);
}

/**
 * Verifies the `X-Firebase-AppCheck` header when enforcement is on.
 *
 * Registered globally, above the routes, so a new endpoint is covered by
 * default. An endpoint that needs an exemption has to be named in
 * [EXEMPT_PATHS], which makes the exemption visible in review rather than
 * implicit in the order somebody registered a middleware.
 */
async function verifyAppCheck(req, res, next) {
  if (!isEnforced()) return next();

  // OPTIONS never carries the header: a browser preflight is generated by the
  // browser itself, and refusing it would break CORS for every legitimate
  // client rather than blocking any illegitimate one.
  if (req.method === 'OPTIONS') return next();

  if (isExempt(req.path)) return next();

  const token = req.get('X-Firebase-AppCheck');
  if (!token) {
    return res.status(401).json({
      error: 'app_check_required',
      message: 'This request must come from an authorised Chokro app.',
    });
  }

  try {
    await admin.appCheck().verifyToken(token);
    return next();
  } catch (err) {
    // The reason is logged and never returned. Distinguishing "expired" from
    // "wrong project" from "malformed" tells someone probing the service which
    // of those they got wrong.
    console.warn('[appCheck] rejected a request:', err.message);
    return res.status(401).json({
      error: 'app_check_failed',
      message: 'This request could not be attested.',
    });
  }
}

/** One line at startup, so the posture is visible in the deploy log. */
function describeEnforcement() {
  return isEnforced()
    ? 'App Check: ENFORCED. Requests without a valid attestation are refused.'
    : 'App Check: not enforced (APP_CHECK_ENFORCED is unset). Any client with '
        + 'a valid ID token is accepted — set it before onboarding a real '
        + 'producer (SEC-10).';
}

module.exports = {
  EXEMPT_PATHS,
  isEnforced,
  isExempt,
  verifyAppCheck,
  describeEnforcement,
};
